export const allergyData = [
  {
    id: 1,
    name: "없음",
    imgUrl: "../../assets/No.svg",
    clickUrl: "",
  },
  {
    id: 2,
    name: "해산물",
    imgUrl: "../../assets/sea.svg",
    clickUrl: "",
  },
  {
    id: 3,
    name: "견과류",
    imgUrl: "../../assets/peanut.svg",
    clickUrl: "",
  },
  {
    id: 4,
    name: "달걀",
    imgUrl: "../../assets/egg.svg",
    clickUrl: "",
  },
  {
    id: 5,
    name: "유제품",
    imgUrl: "../../assets/milk.svg",
    clickUrl: "",
  },
  {
    id: 6,
    name: "육류",
    imgUrl: "../../assets/meat.svg",
    clickUrl: "",
  },
  {
    id: 7,
    name: "밀",
    imgUrl: "../../assets/floor.svg",
    clickUrl: "",
  },
  {
    id: 8,
    name: "벌꿀",
    imgUrl: "../../assets/honey.svg",
    clickUrl: "",
  },
  {
    id: 9,
    name: "인공 첨가물",
    imgUrl: "../../assets/mione.svg",
    clickUrl: "",
  },
  {
    id: 10,
    name: "두류",
    imgUrl: "../../assets/been.svg",
    clickUrl: "",
  },
  {
    id: 11,
    name: "과일류",
    imgUrl: "../../assets/fruit.svg",
    clickUrl: "",
  },
  {
    id: 12,
    name: "향신료",
    imgUrl: "../../assets/spices.svg",
    clickUrl: "",
  },
  {
    id: 13,
    name: "버섯류",
    imgUrl: "../../assets/mush.svg",
    clickUrl: "",
  },
  {
    id: 14,
    name: "생선류",
    imgUrl: "../../assets/seafood.svg",
    clickUrl: "",
  },
];
